#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ function operator-(const TVpVector3&);
#pragma link C++ function operator+(const TVpVector3&, const TVpVector3&);
#pragma link C++ function operator-(const TVpVector3&, const TVpVector3&);
#pragma link C++ function operator*(const Double_t, const TVpVector3&);
#pragma link C++ function operator|(const TVpVector3&, const TVpVector3&);
#pragma link C++ function operator*(const TVpVector3&, const TVpVector3&);
#pragma link C++ function operator==(const TVpVector3&, const TVpVector3&);
#pragma link C++ function operator!=(const TVpVector3&, const TVpVector3&);
#pragma link C++ function norm(TVpVector3&);
#pragma link C++ function normalize(const TVpVector3&);
#pragma link C++ function operator-(const TVpMatrix3x3&);
#pragma link C++ function operator+(const TVpMatrix3x3&, const TVpMatrix3x3&);
#pragma link C++ function operator-(const TVpMatrix3x3&, const TVpMatrix3x3&);
#pragma link C++ function operator*(const Double_t, const TVpMatrix3x3&);
#pragma link C++ function operator*(const TVpMatrix3x3&, const TVpVector3&);
#pragma link C++ function operator*(const TVpMatrix3x3&, const TVpMatrix3x3&);
#pragma link C++ function rotationMatrix(const TVpVector3&, Double_t);
#pragma link C++ function rotationMatrix(const TVpVector3&, const TVpVector3&);
#pragma link C++ function operator==(const TVpMatrix3x3&, const TVpMatrix3x3&);
#pragma link C++ function operator!=(const TVpMatrix3x3&, const TVpMatrix3x3&);
#pragma link C++ function transpose(const TVpMatrix3x3&);

#pragma link C++ class TVpVoxelArray;
#pragma link C++ class TVpMaterial;
#pragma link C++ class TVpMaterialGridData;
#pragma link C++ class TVpMaterialFileData;
#pragma link C++ class TVpMaterialManager;
#pragma link C++ class TVpMaterialDefaults;
#pragma link C++ class TVpSpectrum;
#pragma link C++ class TVpParticle;
#pragma link C++ class TVpPhoton;
#pragma link C++ class TVpVector3;
#pragma link C++ class TVpMatrix3x3;
#pragma link C++ class TVpGeometry;
#pragma link C++ class TVpPitch;
#pragma link C++ class TVpPitchHelical;
#pragma link C++ class TVpPitchSequential;
#pragma link C++ class TVpPointDetector;
#pragma link C++ class TVpPointDetectorArray;
#pragma link C++ class TVpPointDetectorArrayPlanar;
#pragma link C++ class TVpPointDetectorArrayCylindrical;
#pragma link C++ class TVpSource;
#pragma link C++ class TVpSourceIso;
#pragma link C++ class TVpSourcePlaneFanBeam;
#pragma link C++ class TVpSourcePlaneFanBeam2;
#pragma link C++ class TVpSourceCylinderFanBeam;
#pragma link C++ class TVpSourceCylinderFanBeam2;
#pragma link C++ class TVpBowTieFilterCylinder;
#pragma link C++ class TVpBowTieFilter1dTable;
#pragma link C++ class TVpBowTieFilterSomatomDefinition;
#pragma link C++ class TVpObjectLocation;
#pragma link C++ class TVpSolid;
#pragma link C++ class TVpSolidNeighbor;
#pragma link C++ class TVpBox;
#pragma link C++ class TVpSphere;
#pragma link C++ class TVpEllipsoid;
#pragma link C++ class TVpCylinder;
#pragma link C++ class TVpRectangleCut;
#pragma link C++ class TVpPalette;
#pragma link C++ class TVpSinogram;
#pragma link C++ class TVpSolidTester;
#pragma link C++ class TVpSetupTomograph;
#pragma link C++ class TVpSetupDetector;
#pragma link C++ class TVpMath;
#pragma link C++ class TVpDetectorResponse;
#pragma link C++ class TVpSolidStatistics;
#pragma link C++ class TVpRunManager;
#pragma link C++ class TVpRunManagerTomograph;
#pragma link C++ class TVpRunManagerDetector;
#pragma link C++ class TVpAntiscatterGrid;
#pragma link C++ class TVpRandom;
#pragma link C++ class TVpRandom2;
#pragma link C++ class TVpRandom3;
#pragma link C++ class TVpConstant;
#pragma link C++ class TVpIntegral;
#pragma link C++ class TVpVolumeIntegrator;
#pragma link C++ class TVpDimensionsTomograph;
#pragma link C++ class TVpBeamHardeningCorrection;
#pragma link C++ class AVpAbout;

#endif
